# Generated by Django 3.1.7 on 2021-03-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'default_related_name': 'likes'},
        ),
    ]
